### ISSUE TITLE
Not working on mac os and ubuntu ( all the requirement is instaled)

### ISSUE THREAD

**Issue by l4hlou-repo** [devanshbatham/ParamSpider#1]
python paramspider.py --domain yahoo.com
  File "paramspider.py", line 35
    url = f"http://web.archive.org/cdx/search/cdx?url=*.{args.domain}/*&output=txt&fl=original&collapse=urlkey&page=/"
                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by devanshbatham** [comment]
Use with python3 !!

**Comment by devanshbatham** [comment]
F strings are not supported in Python 2

**Comment by l4hlou-repo** [comment]
I already did that but all is false positif

**Comment by devanshbatham** [comment]
Python3 has different subversions, it works on Python 3.7 , for dealing with falsepositives, feed the output of this tool to my another tool "Drishti" , that will filter out the dead domains !
