### ISSUE TITLE
Encoding issue with non-unicode characters

### ISSUE THREAD

**Issue by xxvs** [devanshbatham/ParamSpider#10]
In this case the letter 'ć' or  '\u0107'. 

`Traceback (most recent call last):
  File "paramspider.py", line 67, in <module>
    main()
  File "paramspider.py", line 52, in main
    print('\n'.join(final_uris))
  File "AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0107' in position 2259: character maps to <undefined>
`

**Comment by devanshbatham** [comment]
Can you provide me clear steps to reproduce? Against which domain you were trying (if not Private), that will greatly help me in resolving this issue, 

Thanks

**Comment by xxvs** [comment]
My bad, I launched it from MSYS for some reason (probably stayed there after cloning). Running from cmd is working fine now. 
It was on most Croatian sites, though.

**Comment by devanshbatham** [comment]
Closing this issue , as you confirmed that it is working fine !
