### ISSUE TITLE
gf+paramspider on window 

### ISSUE THREAD

**Issue by gopinath6** [devanshbatham/ParamSpider#16]
i installed gf and paramspider on windows machine, can you explain how can use in windows env?
gf is in C:\Users\nath\go\src\github.com\tomnomnom\gf
ps is in D:\Dropbox\bug\Asus\Web\Tools\OSINT\ParamSpider

**Comment by devanshbatham** [comment]
Hello, I use ArchLinux on my main system and Ubuntu in VM , I never tested GF on windows , I have to install Windows in VM and then test how it works on GF, so it will take time ! Till then you can consider switching to Linux , 

It will take some time for me to come with a ParamSpider + GF on windows guide 

Thanks

**Comment by devanshbatham** [comment]
I am adding a "help needed" label on this , maybe someone who installed this on windows can help !
