### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by shadihh9** [devanshbatham/ParamSpider#21]
when i run gf i have error
![gf](https://user-images.githubusercontent.com/22076930/79807679-4c6edb80-8374-11ea-8a15-17f3195628ab.png)
![Uploading gf2.png…]()

**Comment by devanshbatham** [comment]
Have you installed the GF binary ?

**Comment by shadihh9** [comment]
what do you meaing binray? i do all commnds

**Comment by devanshbatham** [comment]
Go through the installation process of GF once again , You need to put your own GF binary path , not mine , don't just copy paste it , think logically !! You can just Google these basic things !
