### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by scottishhunter1** [devanshbatham/ParamSpider#22]
gf redirect domain.txt
  As you mentioned i follwed but its not working 

no such pattern

**Comment by devanshbatham** [comment]
You gotta paste the .json files in ~/.gf/ folder , then try !

**Comment by scottishhunter1** [comment]
i did it but still not working

**Comment by scottishhunter1** [comment]
can u atleast create a short vedio how to setup i did every thing you said  but its still not working

**Comment by devanshbatham** [comment]
Will try to make it soon, (can't guarantee when tho)
