### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Wwon1oung** [devanshbatham/ParamSpider#23]
can't use it ,always say Can not get target information. maybe i use wrong ...
<img width="489" alt="D1BACD56-B14C-4F1E-8385-57642BF2F83F" src="https://user-images.githubusercontent.com/55070231/79952517-239e3180-84ad-11ea-9af2-0763d163c162.png">

<img width="563" alt="1E4FBB55-97B1-4D50-BA5F-20C70F8ABEEE" src="https://user-images.githubusercontent.com/55070231/79952541-28fb7c00-84ad-11ea-8923-65d522c46fa1.png">

**Comment by devanshbatham** [comment]
I tested it and It is working fine on my side , can you confirm what version of Python you are using ?

**Comment by Wwon1oung** [comment]
![image](https://user-images.githubusercontent.com/55070231/80061907-04fb7180-8565-11ea-9310-e9849dc60951.png)

I find something.em, paramspider search for this 
![image](https://user-images.githubusercontent.com/55070231/80062003-49870d00-8565-11ea-8d13-bf69784bc520.png)

But my national Internet has 'walls' , Can't access this site , yep , so can not request.
haha , always have fun with find bugs.  :)

**Comment by devanshbatham** [comment]
Hello, 

Yup I think that's the probable cause why it is not working, btw have you tried using VPN or any proxy ?

**Comment by Wwon1oung** [comment]
yes,using vpn or proxy can use it!

![image](https://user-images.githubusercontent.com/55070231/80067472-74c32980-8570-11ea-99cc-f48608fa9d87.png)

**Comment by devanshbatham** [comment]
I am glad it worked fine ! 
Closing this issue as your problem is solved !
