### ISSUE TITLE
not work with subdomains

### ISSUE THREAD

**Issue by satishkmr834** [devanshbatham/ParamSpider#25]
when i'm trying to do with subdomain max time it says 
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues

[+] Total unique urls found : 0
[+] Output is saved here : output/b.txt

[!] Total execution time      : 2.0016s

query used :-

python paramspider.py --domain engage.abc.com -o b.txt

**Comment by devanshbatham** [comment]
Hello , 

By default it looks for the parameters in subdomains also(based on the webarchive results ,) and if there will be not results for that subdomain in the web archive data , then it will return 0 urls ,
