### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by cehbikramrock** [devanshbatham/ParamSpider#26]
can not target get information error message !!

**Comment by sumgr0** [comment]
Getting the same error all the targets:

![Screenshot 2020-04-30 at 7 24 15 PM](https://user-images.githubusercontent.com/11391119/80718798-39989b80-8b18-11ea-9dcc-d954ae338d3d.jpg)

**Comment by devanshbatham** [comment]
Hello , 

Well I think web archive is blocking the requests thats why it is not working , I am working on a workaraound , so wait for some time !

**Comment by devanshbatham** [comment]
Hello , I just pushed a Fix , Reclone the repo ! can you confirm whether it is working fine or now ?

**Comment by cehbikramrock** [comment]
thanks buddy !!!! now it work.
