### ISSUE TITLE
SyntaxError: line 40

### ISSUE THREAD

**Issue by 0xShin** [devanshbatham/ParamSpider#30]
Hi, I have just noticed that you updated your script 5 days ago, so I tested out your script but somehow there's an error in line 40.
![image](https://user-images.githubusercontent.com/50789123/81524704-c3503080-9384-11ea-9220-0adb7206a1dd.png)

**Comment by Aaryan9898** [comment]
Whenever i run below command this is what happens

root@vivo1606:~/Downloads/ParamSpider-master# python3 paramspider.py --domain bugcrowd.com --exclude woff,css,js,png,svg,php,jpg


         ___                               _    __       
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/   
                                  /_/                    
                            
                            - coded with <3 by Devansh Batham 
    
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues
root@vivo1606:~/Downloads/ParamSpider-master#

**Comment by PritamKundu** [comment]
![Capture](https://user-images.githubusercontent.com/37695035/83180715-a9189f80-a145-11ea-9b49-d30d29a5ad2d.JPG)

**Comment by devanshbatham** [comment]
@Aaryan9898 reclone the repo , it should work ! 

@PritamKundu install the requests module !
