### ISSUE TITLE
Cannot get target information

### ISSUE THREAD

**Issue by Aaryan9898** [devanshbatham/ParamSpider#31]
root@vivo1606:~/Downloads/ParamSpider-master# python3 paramspider.py --domain bugcrowd.com --exclude woff,css,js,png,svg,php,jpg

         ___                               _    __       
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/   
                                  /_/                    
                            
                            - coded with <3 by Devansh Batham 
    
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues
root@vivo1606:~/Downloads/ParamSpider-master#

**Comment by devanshbatham** [comment]
Reclone the repo , it Should work fine !
