### ISSUE TITLE
unintentional behaviour

### ISSUE THREAD

**Issue by Manjunathan45** [devanshbatham/ParamSpider#34]
Can not get target information while scan the sites at sometimes 
![paramspider](https://user-images.githubusercontent.com/57958243/83354456-6093f880-a376-11ea-9406-939f9ae1e4c1.png)

**Comment by devanshbatham** [comment]
Reclone the repo , it should work fine now (I pushed a fix some days ago) !

**Comment by devanshbatham** [comment]
you have given `-l 3` but the `-l` arg takes a string as argument , By default it is set to `low` , you should use something like `-l high`
