### ISSUE TITLE
I get a bug

### ISSUE THREAD

**Issue by Direwolf-beef** [devanshbatham/ParamSpider#35]
it's show "Can not get target information  If you think this is a bug or unintentional behaviour."
and i change other domain it also bug。thanks

**Comment by b14ckK** [comment]
I get the same bug. Have you solved it?

**Comment by devanshbatham** [comment]
Can you provide clear steps to reproduce ? As it is working fine for me !

**Comment by b14ckK** [comment]
`python3 paramspider.py --domain hackerone.com


         ___                               _    __
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/
                                  /_/

                            - coded with <3 by Devansh Batham

Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues`

**Comment by b14ckK** [comment]
Oh,I know what happened.The server (web.archive.org)  connected failed.I fixed my internet
