### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MastinGood** [devanshbatham/ParamSpider#37]
How can to use gf in windows im struggling following your steps i already install go located in C:\Users\juan\go\bin\gf. Im confused in this part **Note : Replace '/User/levi/go/bin/gf' with the path where gf binary is located in your system.**

**Comment by MastinGood** [comment]
and also in this part **cp -r $GOPATH/src/github.com/tomnomnom/gf/examples ~/.gf**

**Comment by devanshbatham** [comment]
It will be better if you will open this issue in GF's repository ! 

Only open issues related to ParamSpider here !
