### ISSUE TITLE
Python Syntax Error

### ISSUE THREAD

**Issue by Vikas92155** [devanshbatham/ParamSpider#38]
File "paramspider.py", line 40
    url = f"http://web.archive.org/cdx/search/cdx?url=*.{args.domain}/*&output=txt&fl=original&collapse=urlkey&page=/"
                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by Vikas92155** [comment]
It may be due to python 3.x version 
But you can include format() it works perfectly fine.

So it will be
 url = "http://web.archive.org/cdx/search/cdx?url=*.{0}/*&output=txt&fl=original&collapse=urlkey&page=/".format(args.domain)

**Comment by devanshbatham** [comment]
Hello, 

The error is coz of non compatible version of Python you are using ! Am closing this issue anyways
