### ISSUE TITLE
Question? 

### ISSUE THREAD

**Issue by novicered** [devanshbatham/ParamSpider#43]
This only supports .com?

**Comment by devanshbatham** [comment]
No. every tld is supported !!

**Comment by novicered** [comment]
> No. every tld is supported !!

.su doesn't work sadly

**Comment by devanshbatham** [comment]
Hello, 

It just fetches urls from the web archive , if your entered domain has its urls archived in the web archive , then you will get the results , otherwise not ! 

I hope that clears up your doubt

rgds
Devansh

**Comment by novicered** [comment]
> Hello,
> 
> It just fetches urls from the web archive , if your entered domain has its urls archived in the web archive , then you will get the results , otherwise not !
> 
> I hope that clears up your doubt
> 
> rgds
> Devansh

Thank you for answering my questions

**Comment by cyberfalcon123** [comment]
I have a question: the tool interacts with google or any search engine ? because i dont know if a can do the recon phase while paramspider is running (because if the tool interacts with search engines they will ban my IP)
