### ISSUE TITLE
RAM memory saturation

### ISSUE THREAD

**Issue by cyberfalcon123** [devanshbatham/ParamSpider#44]
Some domains, if they are large, saturate the RAM memory and linux kills the process

For exaxmple: python3 paramspider.py -d crd.auctions.yahoo.co.jp

OS: Linux Manjaro  5.4.62-1-MANJARO

**Comment by devanshbatham** [comment]
Can you tell me your machine's specs? Ram? Cores ?

**Comment by cyberfalcon123** [comment]
yesss,  i have 8GB RAM and  i5-6200U 2.8GHz

**Comment by cyberfalcon123** [comment]
Did you try run the command? did you get the same problem?

**Comment by cyberfalcon123** [comment]
Maybe the problem is in Arch linux ... but is weird it must works well without problems no matter whats OS is running

**Comment by cyberfalcon123** [comment]
I was testing the program and if i use the: --level high parameter the probability of RAM saturation with big companies like Yahoo are very high, i hope that information can be helpful

**Comment by devanshbatham** [comment]
Closing this issue as I have revamped this whole project. Check it out.
