### ISSUE TITLE
Import Request Error

### ISSUE THREAD

**Issue by D4rkC0m3t** [devanshbatham/ParamSpider#46]
HI I`m using Python 3.7.4 v   

when i tried to run this script I'm getting this below mentioned error

Traceback (most recent call last):
  File "/root/XSS/ParamSpider/core/requester.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
![python error](https://user-images.githubusercontent.com/73579116/97406027-97b70780-191e-11eb-8f6d-e3871bc74806.PNG)

![PIP](https://user-images.githubusercontent.com/73579116/97406372-23c92f00-191f-11eb-88c7-a7f70d0afd82.PNG)

**Comment by devanshbatham** [comment]
Hello, 

Try installing the module in a virtual env , and re-run the script

**Comment by D4rkC0m3t** [comment]
**_cool man its working now thanks in tons_**

**Comment by theinfosecguy** [comment]
@D4rkC0m3t How did it worked? Can you share?

**Comment by D4rkC0m3t** [comment]
> 
> 
> @D4rkC0m3t How did it worked? Can you share?

Try to install in "Virtualenv"    like below 

(myvirtual) root@KALI:~# pip3 install requests
