### ISSUE TITLE
Tool not working on any of the domain

### ISSUE THREAD

**Issue by akashrpatil** [devanshbatham/ParamSpider#48]
`python3 paramspider.py --domain bugcrowd.com --exclude woff,css,js,png,svg,php,jpg --output bugcrowd.txt
`

`Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues
`

For any of the domain it throws this error please help

**Comment by anubisSs777** [comment]
not found!!!

**Comment by devanshbatham** [comment]
Hello, 

I just tried, and for me, it is working!! 

![image](https://user-images.githubusercontent.com/28016517/100518041-1e2c6680-31b5-11eb-9c73-5bd6c0d3fdbb.png)

**Comment by zerumius** [comment]
> `python3 paramspider.py --domain bugcrowd.com --exclude woff,css,js,png,svg,php,jpg --output bugcrowd.txt `
> 
> `Can not get target information If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues `
> 
> For any of the domain it throws this error please help

you must turn on the VPN, and then try again

**Comment by RoninNakomoto** [comment]
> `python3 paramspider.py --domain bugcrowd.com --exclude woff,css,js,png,svg,php,jpg --output bugcrowd.txt `
> 
> `Can not get target information If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues `
> 
> For any of the domain it throws this error please help

I have checked this issue. This appears related to a previous issue that was closed:
https://github.com/devanshbatham/ParamSpider/issues/41

Your most probable cause is that the waybackmachine website http://web.archive.org/ used by the tool, is encountering technical difficulties. You can double check by actually heading to http://web.archive.org/ and searching for the same domain you have used with param spider. You will notice that the site will sometimes throw a "Fail with status: 503 Service Unavailable" error.
This error is not param spider related.
Please close the issue if you think this has answered your query.

**Comment by RoninNakomoto** [comment]
> Hello,
> 
> I just tried, and for me, it is working!!
> 
> ![image](https://user-images.githubusercontent.com/28016517/100518041-1e2c6680-31b5-11eb-9c73-5bd6c0d3fdbb.png)
@devanshbatham 

This is happening erratically for some users , from time to time, where the server at web.archive.org throws a Fail with status: 503 Service Unavailable" error both as a response to a paramspider request and on the web front-end at the web.archive.org site itself.

Currently paramspider throws a 
```
Can not get target information If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues 
```
when it receives a 503 error.
I worked on a PR that should solve this by cleaning exception handling in the requester module and enabled retries via (--retries and -r) for timeout and http errors . 
 It is here: https://github.com/devanshbatham/ParamSpider/pull/49

**Comment by devanshbatham** [comment]
Hello, 

It should be fixed now, I have merged the hotfix by @RoninNakomoto 

Regards,
Devansh
