### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by nauliajati** [devanshbatham/ParamSpider#5]
on line 35 using Python 3.5
https://github.com/devanshbatham/ParamSpider/blob/3e1c5b1654aafbcf65673408c893af02139a8aaf/paramspider.py#L35

**Comment by devanshbatham** [comment]
I have already mentioned use python 3.7+ , read readme.md before opening an issue !!

**Comment by nauliajati** [comment]
oh my bad sorry that's work now
