### ISSUE TITLE
PLEASE ADD file option in Param Spider

### ISSUE THREAD

**Issue by nichacks35** [devanshbatham/ParamSpider#62]
Means instead of add -d example.com 
we can add test file of url in paramaspider please add in next update

**Comment by xalgord** [comment]
> Means instead of add -d example.com we can add test file of url in paramaspider please add in next update

Hi, I have made a tool for that: https://github.com/xalgord/Mass-ParamSpider

**Comment by devanshbatham** [comment]
Closing this issue as I have revamped this whole project. Check it out.
