### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LvK8** [devanshbatham/ParamSpider#7]
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues                                                                                                          
Traceback (most recent call last):
  File "paramspider.py", line 73, in <module>
    main()
  File "paramspider.py", line 37, in main
    response = unquote(response)
  File "/usr/lib/python3.7/urllib/parse.py", line 629, in unquote
    if '%' not in string:
TypeError: argument of type 'bool' is not iterable

**Comment by devanshbatham** [comment]
Use python 3.7 or higher ! Make sure all dependencies are properly installed !
