### ISSUE TITLE
Issues with running the programm

### ISSUE THREAD

**Issue by KreativeNerd** [devanshbatham/ParamSpider#79]
When I run paramspider -d geeksforgeeks.org after successful installation, I got an error on my Kali Linux 2023.2 as stated below: 
![Paramspider error](https://github.com/devanshbatham/ParamSpider/assets/49385812/cebc2fa9-74d2-4148-add2-208c2dbd41f2)

Traceback (most recent call last):
  File "/home/kali/.local/bin/paramspider", line 5, in <module>
    from paramspider.main import main
  File "/home/kali/.local/lib/python2.7/site-packages/paramspider/main.py", line 93
    logging.info(f"{Fore.YELLOW}[INFO]{Style.RESET_ALL} Fetching URLs for {Fore.CYAN + domain + Style.RESET_ALL}")
                                                                                                                ^
SyntaxError: invalid syntax

**Comment by devanshbatham** [comment]
Use python3

**Comment by KreativeNerd** [comment]
Can you help me fix it?
