### ISSUE TITLE
q:

### ISSUE THREAD

**Issue by n5xxxx** [devanshbatham/ParamSpider#8]
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues
Traceback (most recent call last):
  File "paramspider.py", line 73, in <module>
    main()
  File "paramspider.py", line 37, in main
    response = unquote(response)
  File "D:\Python38\lib\urllib\parse.py", line 614, in unquote
    if '%' not in string:
TypeError: argument of type 'bool' is not iterable

**Comment by devanshbatham** [comment]
Are you sure using pip3 and python 3.7 or higher ?

**Comment by drown95** [comment]
same issue

**Comment by JoeMariePines** [comment]
what version python r u using ?

**Comment by fsocietyon** [comment]
same issue using pip3 and python 3.7.5

**Comment by devanshbatham** [comment]
Pushed a fix (reclone the repo), that should solve your problem ! closing this thread , if you guys face any problems let me know !

**Comment by drown95** [comment]
its now working. thanks bro :)
