### ISSUE TITLE
Unable to run the program

### ISSUE THREAD

**Issue by KreativeNerd** [devanshbatham/ParamSpider#80]
This is the error I got while running the program after a successful installation. Please help
![Paramspider error2](https://github.com/devanshbatham/ParamSpider/assets/49385812/c4599750-fa2a-4ded-b780-d4bfd0b181c9)

**Comment by devanshbatham** [comment]
No space left on device, free up some memory. The error is pretty self explanatory, please google before opening an issue.

**Comment by KreativeNerd** [comment]
Sorry I uploaded a wrong image
