### ISSUE TITLE
Still getting error when Running the program

### ISSUE THREAD

**Issue by KreativeNerd** [devanshbatham/ParamSpider#81]
Please I get an error when I run the program which I think might be from the code. See the image below:
![Paramspider error2](https://github.com/devanshbatham/ParamSpider/assets/49385812/51bceb65-b529-41a4-acee-a568961acbbc)

**Comment by devanshbatham** [comment]
You are still on python2.7


<img width="775" alt="Screenshot 2023-08-14 at 11 33 58 AM" src="https://github.com/devanshbatham/ParamSpider/assets/28016517/a047e4e8-a10d-40d5-8096-dc61d1cd637c">
