### ISSUE TITLE
Endpoints without parameters in the output 

### ISSUE THREAD

**Issue by Aadhie** [devanshbatham/ParamSpider#87]
![Screenshot 2023-08-20 at 5 36 07 PM](https://github.com/devanshbatham/ParamSpider/assets/48092779/d2f1b300-9360-487c-ad89-7fe1ab45bb69)
@devanshbatham Any help from your side?

**Comment by devanshbatham** [comment]
Hey, this is expected behaviour, You can grep for '=' to filer URLs with parameters.
