### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by benjaminbencsik** [devanshbatham/ParamSpider#89]
Traceback (most recent call last):
  File "/home/ben/.local/bin/paramspider", line 8, in <module>
    sys.exit(main())
  File "/home/ben/.local/lib/python3.10/site-packages/paramspider/main.py", line 160, in main
    fetch_and_clean_urls(domain, extensions, args.stream)
  File "/home/ben/.local/lib/python3.10/site-packages/paramspider/main.py", line 96, in fetch_and_clean_urls
    urls = response.text.split()
AttributeError: 'NoneType' object has no attribute 'text'

This keeps happening even though I am fallowing your correct installation from the repository. I am using Ubuntu on WSL.

**Comment by Hacktus** [comment]
I believe that happens when the tool can't fetch a URL 3 times from the web archive.

After the maximum number of retries, if you still get None for the response, the tool doesn't skip and process for the other urls in the list, that's why it crashes, I wrote a small fix for it in my main.py , gonna test it and see if it works and let you know.

**Comment by Gindasundara** [comment]
an error occurred in the ParamSpider installation section, have followed the steps, How to solution ?

**Comment by Hacktus** [comment]
@benjaminbencsik 

I uploaded this python script that does the same but it doesn't clean the URLs as ParamSpider does, you can use it till your issue gets fixed. 

https://github.com/Hacktus/Archive-Fetcher

**Comment by benjaminbencsik** [comment]
> I believe that happens when the tool can't fetch a URL 3 times from the web archive.
> 
> After the maximum number of retries, if you still get None for the response, the tool doesn't skip and process for the other urls in the list, that's why it crashes.

Yeah this is whats happening hopefully there's a fix soon. I am using a urls list on this I should have mentioned.

**Comment by devanshbatham** [comment]
I have added `sys.exit()` to exit the program if it is unable to fetch URLs from wayback even after 3 attempts. I don't there think there is much I can do, as I have no control over the Wayback API and it might not return results sometimes, or sometimes, when it is down.

**Comment by benjaminbencsik** [comment]
> I have added `sys.exit()` to exit the program if it is unable to fetch URLs from wayback even after 3 attempts. I don't think there is much I can do, as I have no control over the Wayback API and it might not return results sometimes, or sometimes, when it is down.

Cool, yeah I will test this thanks for the fast reply/fix.
