### ISSUE TITLE
To run an error

### ISSUE THREAD

**Issue by ladyBird-z** [devanshbatham/ParamSpider#9]
Traceback (most recent call last):
  File "paramspider.py", line 73, in <module>
    main()
  File "paramspider.py", line 37, in main
    response = unquote(response)
  File "C:\python3\lib\urllib\parse.py", line 634, in unquote
    if '%' not in string:
TypeError: argument of type 'bool' is not iterable

**Comment by ladyBird-z** [comment]
Is it my python3 problem?

**Comment by ladyBird-z** [comment]
When I delete the urlib module and download it again, it will run normally.

**Comment by devanshbatham** [comment]
Working fine now ?

**Comment by ladyBird-z** [comment]
Run normally，thanks

**Comment by devanshbatham** [comment]
Duplicate of this thread : https://github.com/devanshbatham/ParamSpider/issues/8
