### ISSUE TITLE
Not able to use tool, looking for help

### ISSUE THREAD

**Issue by hack1or0** [devanshbatham/ParamSpider#93]
I have followed all the steps and all requirement's are met but while typing the command paramspider -d abc.com, i am getting command not found, even saw one of the issues raised but you have asked that person to read requirements.

![Uploading IMG-0986.jpg…]()

**Comment by hack1or0** [comment]
![IMG-0986](https://github.com/devanshbatham/ParamSpider/assets/143463751/8c3300a8-1058-46c4-beba-1dfeb9ba66be)

**Comment by devanshbatham** [comment]
Please set up path of python bins correctly.
