### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by apprahuman** [devanshbatham/ParamSpider#97]
[INFO] Fetching URLs for http://testphp.vulnweb.com
[INFO] Found 6652 URLs for http://testphp.vulnweb.com
[INFO] Cleaning URLs for http://testphp.vulnweb.com
[INFO] Found 515 URLs after cleaning
[INFO] Extracting URLs with parameters
Traceback (most recent call last):
  File "/usr/local/bin/paramspider", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/paramspider/main.py", line 161, in main
    fetch_and_clean_urls(domain, extensions, args.stream, args.proxy, args.placeholder)
  File "/usr/local/lib/python3.10/dist-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/http://testphp.vulnweb.com.txt'

**Comment by ExCave** [comment]
how to fix

**Comment by ramsy0dev** [comment]
@apprahuman  I think you shouldn't provide the http:// with the url in the `-u` flag. According to the README.md it takes just the domain so you should change your command into the following

``` bash
paramspider -u testphp.vulnweb.com
```

**Comment by apprahuman** [comment]
I think error out when its tries to save the result and creating folder with forwards slashes.. // .. its try to change the folder location, this happened to me when I was making one tool too, so what I did was changed the forward slashes with dashes "-" 

`filename=$(echo "$url" | sed 's/\//-/g')`

**Comment by devanshbatham** [comment]
-d expects a domain name and not URL.
